[package]
name = "rust-opengl"
version = "0.1.0"
edition = "2021"
authors = ["Abdulmelik Bekmez"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "*"
glutin = "*"
glam = "0.21.3"
