[package]
name = "rust-opengl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "*"
glutin = "*"
env_logger = "0.9"
log = "0.4"
glam = "0.21.3"
glfw = "0.45.0"
